# Generated by Django 4.2.14 on 2024-08-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(choices=[('EG', 'مصري'), ('SA', 'سعودي'), ('DZ', 'جزائري'), ('AE', 'إماراتي'), ('US', 'أمريكي'), ('IQ', 'عراقي'), ('JO', 'أردني'), ('GB', 'بريطاني'), ('KW', 'كويتي'), ('LB', 'لبناني'), ('LY', 'ليبي'), ('MA', 'مغربي'), ('OM', 'عماني'), ('PS', 'فلسطيني'), ('QA', 'قطري'), ('SY', 'سوري'), ('SD', 'سوداني'), ('TN', 'تونسي'), ('YE', 'يمني'), ('BH', 'بحريني'), ('SO', 'صومالي'), ('MR', 'موريتاني')], default='SA')),
                ('id_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')])),
                ('birth_date', models.DateField()),
                ('health_condition', models.TextField(blank=True)),
                ('avatar', models.ImageField(default='avatar/defaultAvatar.png', upload_to='avatars/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(default='avatar/defaultAvatar.png', upload_to='logos/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
