# Generated by Django 4.2.14 on 2024-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="program", name="age_group",),
        migrations.AddField(
            model_name="program",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="program",
            name="max_age",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="program",
            name="min_age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="program",
            name="sport_category",
            field=models.CharField(
                choices=[
                    ("football", "كرة القدم"),
                    ("judo", "جودو"),
                    ("basketball", "كرة السلة"),
                    ("tennis", "تنس"),
                    ("swimming", "السباحة"),
                    ("volleyball", "كرة الطائرة"),
                    ("karate", "كاراتيه"),
                    ("boxing", "ملاكمة"),
                    ("table_tennis", "تنس الطاولة"),
                    ("gymnastics", "جمباز"),
                    ("water_polo", "كرة الماء"),
                    ("athletics", "ألعاب القوى"),
                    ("handball", "كرة اليد"),
                    ("taekwondo", "تايكوندو"),
                ],
                default="football",
                max_length=50,
            ),
        ),
    ]
