# Generated by Django 4.2.14 on 2024-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_program_registration_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
