# Generated by Django 4.2.14 on 2024-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_program_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="days",
            field=models.CharField(
                choices=[
                    ("sun", "الأحد"),
                    ("mon", "الاثنين"),
                    ("tue", "الثلاثاء"),
                    ("wed", "الأربعاء"),
                    ("thu", "الخميس"),
                    ("fri", "الجمعة"),
                    ("sat", "السبت"),
                ],
                default=[
                    ("sun", "الأحد"),
                    ("mon", "الاثنين"),
                    ("tue", "الثلاثاء"),
                    ("wed", "الأربعاء"),
                    ("thu", "الخميس"),
                    ("fri", "الجمعة"),
                    ("sat", "السبت"),
                ],
                max_length=255,
            ),
        ),
    ]
