# Generated by Django 4.2.14 on 2024-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_program_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="avatar",
            field=models.ImageField(
                default="avatar/defaultAvatar.png", upload_to="coach_avatars/"
            ),
        ),
    ]
