# Generated by Django 4.2.14 on 2024-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0010_alter_coach_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="avatar",
            field=models.ImageField(
                default="avatar/profile-circle.png", upload_to="coach_avatars/"
            ),
        ),
    ]
