# Generated by Django 4.2.14 on 2024-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0004_enrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "معلق"),
                    ("in_progress", "جاري"),
                    ("ended", "منتهي"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
