# Generated by Django 4.2.14 on 2024-08-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='enrollment',
        ),
    ]
